hw03_frequency_analysis
nikitagreb/otus-go-test pull request #3
Opened 2022-06-21 14:24 UTC by nikitagreb

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-22 03:55 UTC, agneum requested changes
Спасибо за выполненное задание. 
Хорошая работа, однако не хватает новых юнит-тестов, поэтому возвращаю решение на доработку

Итого: 5 баллов из 10

2022-06-22 03:55 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		}
Можно не проверять наличие слова в мапе и сразу делать инкремент

2022-06-22 03:55 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		if outPutStr[i-1].Count != outPutStr[i].Count {
Предлагаю отсортировать лексикографически в том же вызове функции sort.Slice, где происходит сортировка по счётчику. Это позволит получить сразу отсортированный слайс

2022-07-04 15:00 UTC, nikitagreb commented on hw03_frequency_analysis/top.go
> +		}
@agneum 

```suggestion
		_, ok := wordCounts[word]
		if ok {
			wordCounts[word]++
		}
```

в этом случае падают тесты с ошибкой 

```suggestion
		--- FAIL: TestTop10 (0.00s)
    --- PASS: TestTop10/no_words_in_empty_string (0.00s)
    --- FAIL: TestTop10/positive_test (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```

что-то не пойму в чем дело

2022-07-04 15:09 UTC, nikitagreb commented on hw03_frequency_analysis/top.go
> +		if outPutStr[i-1].Count != outPutStr[i].Count {
тут не понял комментария если честно, можно пример кода?

2022-07-04 16:00 UTC, nikitagreb commented on hw03_frequency_analysis/top.go
> +		}
короче переписал я метод вроде норм

2022-07-04 16:01 UTC, nikitagreb commented
@agneum переписал метод добавил юнит тест

2022-07-08 15:56 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		if outPutStr[i-1].Count != outPutStr[i].Count {
Сортировка слайса выглядит следующим образом
```go
	sort.Slice(outPutStr, func(i, j int) bool {
		return outPutStr[i].Count > outPutStr[j].Count
	})
```
Предлагаю в функции-компараторе сравнить элементы не только по Count, но и по Word, если Count равны.
Итоговый слайс `outPutStr` получится отсортированным должным образом, и не потребуются дополнительные сортировки и временные переменные

2022-07-08 15:57 UTC, agneum approved these changes
Спасибо за правки и тесты. Хорошая работа.
Итого: 9 баллов из 10. Принято

2022-08-30 14:56 UTC, merged